spring.application.name=underwearshop
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
ADMIN_LOGIN=ADMIN
ADMIN_PASSWORD=ADMIN

novapost.api-key:bcb8e7d98a7b2b423c4fe3878ea14f85
novapost.base-url:https://api.novaposhta.ua/v2.0/json

telegram.bot.token=8859753544:AAEze_j3fJ-eWoNdgzK43NadAKYzvWnYGrc
telegram.bot.username=@zuna333_bot

spring.mail.host=smtp.ukr.net
spring.mail.port=465
spring.mail.username=markrrr@ukr.net
spring.mail.password=iJUsExTxr2fjcu2L
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
mail.from=markrrr@ukr.net
#sendgrid.api-key=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
